name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: logstash-with-avro
  REGISTRY_NAME: docker.pkg.github.com
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        
      
      - name: Build and tag Docker image
        run: docker build -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY_NAME }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/${{ github.repository }}:latest
